[package]
name = "alloy"
version = "0.1.0"
authors = ["Atahan YorgancÄ± <atahanyorganci@hotmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"
structopt = "0.3.25"
rustyline = "9.1.2"
